apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
    inbound:
        - name: auth-svc
          port: 8081
          type: REST
          networkVisibility: Public
          context: /
